// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6-uoXPRI2vKVTKb-TeTgGGrXqoNuISmk',
    appId: '1:964813443124:web:ef46bb6f82fca730ef3a61',
    messagingSenderId: '964813443124',
    projectId: 'solulabauth-69cb8',
    authDomain: 'solulabauth-69cb8.firebaseapp.com',
    storageBucket: 'solulabauth-69cb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nkqf3i2PJlN0hE9Bz6s898HjsOHV_HI',
    appId: '1:964813443124:android:60b4dfb8e8378646ef3a61',
    messagingSenderId: '964813443124',
    projectId: 'solulabauth-69cb8',
    storageBucket: 'solulabauth-69cb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDI8_oqtgz8-LUQ-xIJXkjHV9OTlJYjPU',
    appId: '1:964813443124:ios:7e647c21b6ae0873ef3a61',
    messagingSenderId: '964813443124',
    projectId: 'solulabauth-69cb8',
    storageBucket: 'solulabauth-69cb8.appspot.com',
    androidClientId: '964813443124-5dtsu54g429kq9h3kvasc3bsed0cdii4.apps.googleusercontent.com',
    iosClientId: '964813443124-1rrh5vehrqgtt3uq5picqsrftqllrrak.apps.googleusercontent.com',
    iosBundleId: 'com.example.solulab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDI8_oqtgz8-LUQ-xIJXkjHV9OTlJYjPU',
    appId: '1:964813443124:ios:7e647c21b6ae0873ef3a61',
    messagingSenderId: '964813443124',
    projectId: 'solulabauth-69cb8',
    storageBucket: 'solulabauth-69cb8.appspot.com',
    androidClientId: '964813443124-5dtsu54g429kq9h3kvasc3bsed0cdii4.apps.googleusercontent.com',
    iosClientId: '964813443124-1rrh5vehrqgtt3uq5picqsrftqllrrak.apps.googleusercontent.com',
    iosBundleId: 'com.example.solulab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6-uoXPRI2vKVTKb-TeTgGGrXqoNuISmk',
    appId: '1:964813443124:web:d197ab13b9dcf1f0ef3a61',
    messagingSenderId: '964813443124',
    projectId: 'solulabauth-69cb8',
    authDomain: 'solulabauth-69cb8.firebaseapp.com',
    storageBucket: 'solulabauth-69cb8.appspot.com',
  );

}